# Generated by Django 3.0.6 on 2020-10-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokuty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenseDate', models.DateField()),
                ('reason', models.CharField(max_length=100)),
                ('price', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fridgeDate', models.DateField()),
                ('user', models.CharField(max_length=100)),
                ('penaltyPrice', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomeDate', models.DateField()),
                ('user', models.CharField(max_length=100)),
                ('price', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveSmallIntegerField()),
                ('teamPenalty', models.BooleanField()),
                ('trainingPenalty', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PenaltyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penaltyDate', models.DateField()),
                ('user', models.CharField(max_length=100)),
                ('penaltyName', models.CharField(max_length=200)),
                ('penaltyPrice', models.PositiveSmallIntegerField()),
                ('payed', models.BooleanField()),
            ],
        ),
    ]
