# Generated by Django 3.0.6 on 2020-10-18 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokuty', '0002_expenses_fridge_income_penalty_penaltyrecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expenses',
            new_name='Expense',
        ),
    ]
