# Generated by Django 3.0.6 on 2020-10-18 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokuty', '0003_auto_20201018_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penaltyrecord',
            name='user',
        ),
        migrations.AddField(
            model_name='penaltyrecord',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
