# Generated by Django 3.0.6 on 2020-10-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokuty', '0004_auto_20201018_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penaltyrecord',
            name='user_id',
        ),
        migrations.AddField(
            model_name='penaltyrecord',
            name='user',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
