# Generated by Django 3.0.6 on 2020-10-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokuty', '0005_auto_20201018_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='penaltyrecord',
            name='user_id',
            field=models.PositiveSmallIntegerField(default=None),
        ),
    ]
