# Generated by Django 3.0.6 on 2020-10-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokuty', '0006_penaltyrecord_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penaltyrecord',
            name='user_id',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
