# Generated by Django 3.0.6 on 2020-10-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokuty', '0008_auto_20201018_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penaltyrecord',
            name='user_id',
        ),
        migrations.AddField(
            model_name='penaltyrecord',
            name='userId',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
